### PR TITLE
Remove customized config files and use the ones packaged with kartotherian

### PR DESCRIPTION
**Pull request by adamwight**
This allows config to change along with code.  We don't need the
template to be quite so flexible, I suspect.

### CODE REVIEW

**Comment by WMDE-Fisch** [comment]
When I just try this and start running the server I get 
```
Error: Postgis Plugin: could not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Cannot assign requested address\n\tIs the server running on host \"localhost\" (::1) and accepting\n\tTCP/IP connections on port 5432?\nConnection string: 'host=localhost dbname=gis user=default connect_timeout=4
```

**Comment by WMDE-Fisch** [comment]
Rebased on top of current main.

**Comment by WMDE-Fisch** [comment]
Does not work for me. I get 
```
Error: Postgis Plugin: could not connect to server: Connection refused
Is the server running on host \"localhost\" (127.0.0.1) and accepting
TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
Is the server running on host \"localhost\" (::1) and accepting
TCP/IP connections on port 5432?
Connection string: 'host=localhost dbname=gis user=default connect_timeout=4'
```

**Comment by adamwight** [comment]
We have it working locally, I'll merge now.

**Pull request merged**
